sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        sQezIvrIZeA+d1bKFmBdh2w/SDilX+MDKmlqn9QApCuH7Yl8lhkJaG8Lc8hsXL/P4lAL4ldD8Sg7cHE3/4XDILPx2FzQUvdzCH+2LTYoGtX0vM4ea0gJyJiDllttX6K2YrElCUz0HpsoRPPiONJMmi2/ASlW3pHpxocSlAWGfrkiJImjfvr2c9X1lCNPu7HeBbOdcRDUNf6E6Dm3swC4DiTQxRFAhzfZP7nRGQ1xwANIa4Y+Bq2oyoC4oHNdQI0CRohjVViHXxw9XaxUmGPxx/OPFLgZFPqPfpMvz5O39vjervB3IQy/J/uEcWwxPmZXs9OhnxdSwbQJICYjQAFib2Z+qyc+1jwHNdsckiDC41IjfmUe4OOEv2A2V4HeXtcSItCjUEktBzw+ne+M8t9scJOFQ1h58pRnOi9MeOTBxZeD99CXqtmCenTWWo4+JAsXhl3nWQ61QvX/yvQvw6HlF8PMdFbrHaRaSxdPxGhAyOrhgqP6CTnIdBEmMok/oGN/nz/Mip803EL5LPaJkiWXNBnHoyr54qptdq5I4mIKQHQLNi7XY5AMf6Y7B1ZjpWmGU4BdYHYUjh6IU7JR9sFMdbcXRbZldxB9LQuwVyRki0UD8fK2HQeJzzvsEJgaQ7uJgwgM6GenIrvi/sT9/cjIEDJ86YA+AYa7CgagDBce+mY=
    - secure: >-
        tj97rPqNvQeeh9KS/kTtEd9GFnTX5X5FknfICrVtmbbmmpQy6O4Wxd+tgYViTO3tY1lHgWdEM4NLuqvsJmdnXp1wvmhujqdlJldyYiZ9edB3x3lGAgRbOK63Etbd+0QHjiRqh6efMC5yekahF+5TkiW2deep9NlqVb0BQk3cbNE/HbgtonydQQjSbuUY7JOE285OrrxcfAkJKY69NgBuKcL51xpSSSuPF8GHj/0Akse7VLX1U0kbmtK64K46VHTEoDCpuyL8cKcNQy/+SLYzsdLed3z8VGtarwTea3eSkAXHayzuY1YgyD7aUaj9DGn4W1DltNlAyFOwSQSAs6Pe/GDhz1y3pPYc9fJ80ngfMxTstq3DMSagGRamcFly4+wOZoPp/986NJXMEHWb5wqwQ/K5cPCXKw1YafZMgeHprirUrwk0cYrx+uZ4VScHxteL6G1SfWbt6mXPpXXaepTDwtH2mfF0XRA3L4PMCAEp1TCuOQuvZVXk6yu4v37ESMfTaVLPaxc9mi/7AKB21N6LU/bPMTrQQHTRw0h5lopabF4fshNgFZ7PiY4mW3DE0UkfjqOMEhxM5orhZt12mdTD7vYmKLQGn17rHVYVjZCEZx8F4E28ddttFdUFl4zG9xjVT44NVsWx10T3wkcoHVjeo3SyP/OFbh0Lr+X/e86WbS4=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
